### PR TITLE
Add locale option to Element component

### PR DESCRIPTION
**Pull request by joshnuss**
- Adds locale option to <Elements/> component
- Updates changelog

### CODE REVIEW

**Comment by el-sonny** [comment]
HI @joshnuss will this feature be documented? At the moment I'm not sure how to set it up, just passing a locale string seems to not work per typescript error.

**Comment by joshnuss** [comment]
Hi @el-sonny,

What version of the npm package are you using? What's the typescript error?

**Comment by el-sonny** [comment]
Hi @joshnuss I'm using 0.0.22 and the error is:

```
Type '{ stripe: Stripe; clientSecret: string; locale: string; elements: StripeElements; }' is not assignable to type '{ stripe: Stripe; clientSecret?: string; elements?: StripeElements; theme?: "flat" | "stripe" | "night" | "none"; variables?: { fontFamily?: string; fontSmooth?: string; ... 52 more ...; borderRadius?: string; }; rules?: { ...; }; labels?: "above" | "floating"; loader?: "auto" | ... 1 more ... | "always"; }'.
  Object literal may only specify known properties, and '"locale"' does not exist in type '{ stripe: Stripe; clientSecret?: string; elements?: StripeElements; theme?: "flat" | "stripe" | "night" | "none"; variables?: { fontFamily?: string; fontSmooth?: string; ... 52 more ...; borderRadius?: string; }; rules?: { ...; }; labels?: "above" | "floating"; loader?: "auto" | ... 1 more ... | "always"; }'.ts(2322)
```

**Comment by joshnuss** [comment]
I tested locally and it works for me.

What version of `@stripe/stripe-js` are you using? Maybe it's outdated?

**Comment by el-sonny** [comment]
I have version 1.48.0 of @stripe/stripe-js could you give an example of your usage just to make sure I'm doing it correctly?

**Comment by joshnuss** [comment]
Here's the code I'm using:

```svelte
<script lang="ts">
  import { Elements } from 'svelte-stripe'
  import { loadStripe } from '@stripe/stripe-js'
  import type { Stripe } from '@stripe/stripe-js'
  import { onMount } from 'svelte'
  import { PUBLIC_STRIPE_KEY } from '$env/static/public'

  let stripe: Stripe | null = null

  onMount(async () => {
    stripe = await loadStripe(PUBLIC_STRIPE_KEY)
  })
</script>

{#if stripe}
  <Elements {stripe} locale="en"/>
{/if}
```

**Pull request merged**
